INSERT INTO categories (main_category, category_name) VALUES
-- Fashion & Accessories
('Fashion & Accessories', 'Handbags'),
('Fashion & Accessories', 'Backpacks'),
('Fashion & Accessories', 'Wallets'),
('Fashion & Accessories', 'Luggage – Suitcase and Trolleys'),
('Fashion & Accessories', 'Luggage – Travel Accessories'),
('Fashion & Accessories', 'Watches'),
('Fashion & Accessories', 'Eyewear – Sunglasses, Frames and Zero Power Eye Glasses'),
-- Apparel
('Apparel', 'Apparel – Women''s Innerwear and Lingerie'),
('Apparel', 'Apparel – Men''s T-Shirts (except Tank Tops and Full Sleeve Tops)'),
('Apparel', 'Apparel – Sarees and Dress Materials'),
('Apparel', 'Apparel – Ethnic Wear'),
('Apparel', 'Apparel – Dress'),
('Apparel', 'Apparel – Shirts'),
('Apparel', 'Apparel – Other products'),
('Apparel', 'Apparel – Accessories'),
-- Footwear
('Footwear', 'Shoes'),
('Footwear', 'Flip Flops'),
('Footwear', 'Kids Shoes'),
('Footwear', 'Sports – Footwear'),
-- Jewellery
('Jewellery', 'Fashion Jewellery'),
('Jewellery', 'Silver Jewellery'),
('Jewellery', 'Fine Jewellery – Studded'),
('Jewellery', 'Fine Jewellery – Unstudded and Solitaire'),
-- Home & Kitchen
('Home & Kitchen', 'Cookware, Tableware and Dinnerware'),
('Home & Kitchen', 'Home Decor Products'),
('Home & Kitchen', 'Bedsheets, Blankets and Covers'),
('Home & Kitchen', 'Cushion Covers'),
('Home & Kitchen', 'Wall Art'),
('Home & Kitchen', 'Home Fragrance and Candles'),
('Home & Kitchen', 'Rugs and Doormats'),
('Home & Kitchen', 'Kitchen Tools and Supplies – Choppers, Knives, Bakeware and Accessories'),
('Home & Kitchen', 'Home Furnishing (Excluding Curtain and Curtain Accessories)'),
('Home & Kitchen', 'Curtains and Curtain Accessories'),
('Home & Kitchen', 'Clocks'),
-- Beauty
('Beauty', 'Beauty – Haircare, Bath and Shower'),
('Beauty', 'Beauty – Make-up'),
('Beauty', 'Beauty – Fragrance'),
('Beauty', 'Luxury Beauty'),
('Beauty', 'Face Wash'),
('Beauty', 'Moisturiser Cream'),
('Beauty', 'Sunscreen'),
('Beauty', 'Deodorants'),
('Beauty', 'Beauty – Other products'),
-- Electronics
('Electronics', 'Mobile Phones'),
('Electronics', 'Tablets'),
('Electronics', 'Laptops'),
('Electronics', 'Television'),
('Electronics', 'Speakers'),
('Electronics', 'Headsets, Headphones and Earphones'),
('Electronics', 'Smart Watches and Accessories'),
('Electronics', 'Power Banks and Chargers'),
('Electronics', 'Cases, Covers and Skins, and Screen Guards'),
('Electronics', 'Camera and Camcorder'),
('Electronics', 'Camera Accessories'),
('Electronics', 'Electronic Devices (Excluding TV, Camera and Camcorder, Camera Lenses and Accessories, GPS Devices and Speakers)'),
('Electronics', 'Accessories – Electronics, PC and Wireless'),
-- Toys
('Toys', 'Toys – Games and Puzzles, Boards Games, Adult Games and Building Sets'),
('Toys', 'Toys – Infant and Pre-school Toys (Electronic and Non-Electronic)'),
('Toys', 'Toys – Plush Toys, Action Figures and Dolls'),
('Toys', 'Toys – Other products'),
('Toys', 'Toys – Drones'),
-- Grocery
('Grocery', 'Grocery and Gourmet – Other products'),
('Grocery', 'Grocery – Dried Fruits and Nuts'),
('Grocery', 'Grocery – Hampers and gifting'),
('Grocery', 'Grocery and Gourmet – Beverages'),
-- Sports & Fitness
('Sports & Fitness', 'Gym Equipment'),
('Sports & Fitness', 'Gym Weights'),
('Sports & Fitness', 'Bicycles'),
('Sports & Fitness', 'Sports – Cricket and Badminton Equipments, Tennis, Table Tennis, Squash, Football, Volleyball, Basketball, Throwball and Swimming'),
('Sports & Fitness', 'Sports – Other products'),
-- Health
('Health', 'Health and Household – Vitamins and Mineral Health Supplements'),
('Health', 'Health and Household – Other products'),
('Health', 'Health and Household – Household Cleaning, Laundry, Air Fresheners, Personal Hygiene (Hand Wash)'),
-- Baby
('Baby', 'Baby – Other products'),
('Baby', 'Baby – Diapers'),
('Baby', 'Baby Strollers'),
-- Furniture
('Furniture', 'Large Furniture – Sofa, Beds, Wardrobes, Recliners, Living & Dining room chairs and tables'),
('Furniture', 'Office Furniture – Study Table, Office and Gaming Chairs'),
('Furniture', 'Mattresses'),
('Furniture', 'Bean Bags and Inflatables'),
-- Pet
('Pet', 'Pet Accessories, including Apparel, Collar, Leash and Harness'),
('Pet', 'Pet Foods'),
('Pet', 'Pet – Other products'),
-- Automotive
('Automotive', 'Automotive Accessories – Floor Mats, Seat, Car and Bike Covers'),
('Automotive', 'Automotive – Other products'),
-- Books & Media
('Books & Media', 'Books')
ON CONFLICT (category_name) DO NOTHING;
